### ISSUE TITLE
rmdup index error

### ISSUE THREAD

**Issue by mriglobal** [shenwei356/seqkit#127]
I am trying to run rmdup on an enormous multifasta - 2.4TB in size. I recognize that the sheer size may be an issue, but I'm not getting a RAM problem. I will be attempting to split the file into smaller ones and run rmdup on them until I can track down what may be erroneous, but in the meantime I wanted to bring this to your expertise.

The error is:
```$ seqkit rmdup -s total.blastdl.fasta > total.blastdl.dedupe.fasta
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/shenwei356/bio/seqio/fastx.(*Reader).read(0xc00017e000)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/bio/seqio/fastx/reader.go:229 +0x7b1
github.com/shenwei356/bio/seqio/fastx.(*Reader).Read(...)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/bio/seqio/fastx/reader.go:141
github.com/shenwei356/seqkit/seqkit/cmd.glob..func20(0x1220000, 0xc00000d680, 0x1, 0x2)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/rmdup.go:90 +0x43e
github.com/spf13/cobra.(*Command).execute(0x1220000, 0xc00000d640, 0x2, 0x2, 0x1220000, 0xc00000d640)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:835 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1220280, 0xc00000d560, 0xc0002905d0, 0xc00000e020)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:919 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:869
github.com/shenwei356/seqkit/seqkit/cmd.Execute()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/root.go:52 +0x31
main.main()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/main.go:58 +0x20
```

**Comment by mriglobal** [comment]
Update:
I get a very similar error when trying to run seqkit split on a 100GB fasta file
```seqkit split -p 10 tmp.fasta 
[INFO] split into 10 parts
[INFO] read sequences ...
panic: runtime error: index out of range [-1]

goroutine 16 [running]:
github.com/shenwei356/bio/seqio/fastx.(*Reader).read(0xc0000f2240)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/bio/seqio/fastx/reader.go:229 +0x7b1
github.com/shenwei356/bio/seqio/fastx.(*Reader).Read(...)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/bio/seqio/fastx/reader.go:141
github.com/shenwei356/bio/seqio/fastx.(*Reader).ChunkChan.func1(0xa, 0xc0000f2240, 0xc0000aa240)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/bio/seqio/fastx/reader.go:471 +0x99
created by github.com/shenwei356/bio/seqio/fastx.(*Reader).ChunkChan
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/bio/seqio/fastx/reader.go:465 +0x8c```

**Comment by shenwei356** [comment]
It's a bug rarely happen. Try this fix:

- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/4579585/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4579583/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4579581/seqkit_darwin_amd64.tar.gz)

**Comment by shenwei356** [comment]
@mriglobal solved?

**Comment by shenwei356** [comment]
@mriglobal Hi, is this solved? I have to make sure it's fixed before releasing a new version.
