### ISSUE TITLE
seqkit fish error

### ISSUE THREAD

**Issue by ryys1122** [shenwei356/seqkit#135]
seqkit fish error when there are Ns in ref genome,
```
seqkit fish -p 0,4,0,0 -F GGCACAGGCCACAGGGAAGAAGG Zea_mays.AGPv4.32.fa 
panic: Could not align sequences: align: illegal letter 'N' at position 623272 in rSeq

goroutine 1 [running]:
github.com/shenwei356/seqkit/seqkit/cmd.PairwiseAlignSW(0xc0000e0000, 0xc0002ce400, 0xc0002418c0, 0x0)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/seq_detect.go:289 +0x837
github.com/shenwei356/seqkit/seqkit/cmd.(*SeqDetector).detectOnce(0xc0002ce300, 0xc0002dfbf8, 0x7ff8000000000001, 0x7ff8000000000001, 0x7f176a89ad60, 0xc000452380, 0xc000452380)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/seq_detect.go:135 +0x1e1
github.com/shenwei356/seqkit/seqkit/cmd.(*SeqDetector).Detect(0xc0002ce300, 0xc0002dfbf8, 0x124d1500, 0x200077c4, 0xc000a82000, 0x124d15b5)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/seq_detect.go:92 +0x243
github.com/shenwei356/seqkit/seqkit/cmd.glob..func8(0x125d700, 0xc0000d8870, 0x1, 0x5)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/fish.go:234 +0x8c4
github.com/spf13/cobra.(*Command).execute(0x125d700, 0xc0000d8820, 0x5, 0x5, 0x125d700, 0xc0000d8820)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x125cc80, 0xc00000d580, 0xc00038f680, 0xc00000e020)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:887
github.com/shenwei356/seqkit/seqkit/cmd.Execute()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/root.go:52 +0x31
main.main()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/main.go:58 +0x20
```

**Comment by shenwei356** [comment]
@bsipos

**Comment by bsipos** [comment]
Due to the limitations of the alignment library `seqkit fish` does not support Ns. I suggest replacing Ns with a random nucleotide, which is a strategy applied internally in several aligners.
