### ISSUE TITLE
runtime: out of memory: cannot allocate 4194304-byte block (3933634560 in use)

### ISSUE THREAD

**Issue by moldach** [shenwei356/seqkit#153]
I'm getting an `out of memory` issue when trying to sort a `101Gb` `fastq` file.

I've got PE fastq files, each `101 Gb`, for which the reads don't seem to match (according to BWA-MEM): `[mem_sam_pe] paired reads have different names: "E00434:224:H32MMCCX2:8:1101:15067:1819", "E00434:224:H32MMCCX2:8:1101:14742:1819"`

So I'm trying to use `seqkit` to sort each of these files before running through BWA-MEM again; this is the error I observer.

```
(base) [moldach@synergy DeconSeqProband]$ seqkit sort --quiet R1_clean.fq > R1_sorted_cleaned.fastq
runtime: out of memory: cannot allocate 4194304-byte block (3933634560 in use)
fatal error: out of memory

goroutine 1 [running]:
runtime.throw(0x866cf25, 0xd)
/usr/local/go/src/runtime/panic.go:1116 +0x6a fp=0x9c918c8 sp=0x9c918b4 pc=0x80777ba
runtime.(*mcache).refill(0xf77af088, 0x9)
/usr/local/go/src/runtime/mcache.go:140 +0xe9 fp=0x9c918d8 sp=0x9c918c8 pc=0x805bc89
runtime.(*mcache).nextFree(0xf77af088, 0x9, 0x0, 0xe3e051e0, 0x80658df)
/usr/local/go/src/runtime/malloc.go:868 +0x79 fp=0x9c918f4 sp=0x9c918d8 pc=0x80521b9
runtime.mallocgc(0x30, 0x0, 0xf77af000, 0xff7fff80)
/usr/local/go/src/runtime/malloc.go:1036 +0x618 fp=0x9c91948 sp=0x9c918f4 pc=0x8052968
runtime.rawbyteslice(0x27, 0x0, 0x0, 0x0)
/usr/local/go/src/runtime/string.go:272 +0x94 fp=0x9c91964 sp=0x9c91948 pc=0x8091334
runtime.stringtoslicebyte(0x0, 0xff7fffb0, 0x27, 0x100000, 0xff7fffb0, 0x27)
/usr/local/go/src/runtime/string.go:161 +0x92 fp=0x9c91984 sp=0x9c91964 pc=0x8090dd2
github.com/shenwei356/bio/seqio/fastx.(*Record).Clone(...)
/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/bio/seqio/fastx/records.go:22
github.com/shenwei356/seqkit/seqkit/cmd.glob..func27(0x8d8cf60, 0x980cc20, 0x1, 0x2)
/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/sort.go:164 +0x27c7 fp=0x9c91ec8 sp=0x9c91984 pc=0x8551c87
github.com/spf13/cobra.(*Command).execute(0x8d8cf60, 0x980cc10, 0x2, 0x2, 0x8d8cf60, 0x980cc10)
/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:846 +0x1e3 fp=0x9c91f30 sp=0x9c91ec8 pc=0x835b723
github.com/spf13/cobra.(*Command).ExecuteC(0x8d8c300, 0x98222b0, 0x0, 0x1)
/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:950 +0x291 fp=0x9c91f98 sp=0x9c91f30 pc=0x835c081
github.com/spf13/cobra.(*Command).Execute(...)
/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:887
github.com/shenwei356/seqkit/seqkit/cmd.Execute()
/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/root.go:53 +0x23 fp=0x9c91fc4 sp=0x9c91f98 pc=0x851d923
main.main()
/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/main.go:58 +0x17 fp=0x9c91fc8 sp=0x9c91fc4 pc=0x8570827
runtime.main()
/usr/local/go/src/runtime/proc.go:203 +0x1fd fp=0x9c91ff0 sp=0x9c91fc8 pc=0x8079f5d
runtime.goexit()
/usr/local/go/src/runtime/asm_386.s:1337 +0x1 fp=0x9c91ff4 sp=0x9c91ff0 pc=0x80a36c1
```

From benchmarks how much memory is expected to sort a `~100Gb` fastq file? We have up to `3Tb` of RAM available on our remote server.

**Comment by shenwei356** [comment]
It's not suitable for large FASTQ files.

**Comment by moldach** [comment]
Thank you, for those of you interested in a working solution I needed to use [fastq tool's sort function ](https://github.com/dcjones/fastq-tools). As an aside, I had also used DeconSeq to clean my FASTQ reads prior to using BWA. I got errors and the reason was there were cases in which reads did not have pairs so I also used [fastq-pair](https://github.com/linsalrob/fastq-pair) to solve this.

Along a similar line, I'm trying to use SeqKit's `stats` function to get information on raw FASTQ files and cleaned FASTQ files (with DeconSeq) but I'm getting an error. Could this also be due to the large size of the files?


```
seqkit stats -a CG00010P_R1.fastq.gz CG00010P_R2.fastq.gz > raw_report.txt


fatal error: slice bounds out of range

runtime stack:
runtime.throw(0x86751d7, 0x19)
        /usr/local/go/src/runtime/panic.go:1116 +0x6a
runtime.panicCheck1(0x806cf3c, 0x86751d7, 0x19)
        /usr/local/go/src/runtime/panic.go:34 +0xb9
runtime.goPanicSliceBU(0x3bc, 0x51)
        /usr/local/go/src/runtime/panic.go:119 +0x37
runtime.(*pageAlloc).update(0x8d93aa4, 0xeec00000, 0x12e00, 0x1)
        /usr/local/go/src/runtime/mpagealloc.go:430 +0x47c
runtime.(*pageAlloc).grow(0x8d93aa4, 0xeec00000, 0x25c00000)
        /usr/local/go/src/runtime/mpagealloc.go:394 +0x175
runtime.(*mheap).grow(0x8d93aa0, 0x12d3e, 0x0)
        /usr/local/go/src/runtime/mheap.go:1325 +0x7f
runtime.(*mheap).allocSpan(0x8d93aa0, 0x12d3e, 0x100, 0x8da5788, 0x3f3070e8)
        /usr/local/go/src/runtime/mheap.go:1124 +0x5e2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:871 +0x4c
runtime.(*mheap).alloc(0x8d93aa0, 0x12d3e, 0x8d90001, 0x9602e00)
        /usr/local/go/src/runtime/mheap.go:865 +0x63
runtime.largeAlloc(0x25a7c000, 0x8d90100, 0x1)
        /usr/local/go/src/runtime/malloc.go:1152 +0x76
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:1047 +0x39
runtime.systemstack(0x90a3ce0)
        /usr/local/go/src/runtime/asm_386.s:395 +0x53
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1041

goroutine 14 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_386.s:356 fp=0x9148d58 sp=0x9148d54 pc=0x80a1e90
runtime.mallocgc(0x25a7c000, 0x0, 0xa480000, 0xa380000)
        /usr/local/go/src/runtime/malloc.go:1046 +0x6aa fp=0x9148dac sp=0x9148d58 pc=0x80529fa
runtime.growslice(0x85d7ec0, 0x7021e000, 0x3c3f800, 0x3c3f800, 0x3c3f801, 0x8, 0x0, 0x3c3f800)
        /usr/local/go/src/runtime/slice.go:175 +0x111 fp=0x9148df4 sp=0x9148dac pc=0x808d781
github.com/shenwei356/seqkit/seqkit/cmd.glob..func30.3(0x937f080, 0x9110e00, 0x1, 0x0, 0x866a4f2, 0x9, 0x9110d40, 0x9110d00, 0x8667480, 0x1, ...)
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/stat.go:355 +0x543 fp=0x9148fa0 sp=0x9148df4 pc=0x856d5a3
runtime.goexit()
        /usr/local/go/src/runtime/asm_386.s:1337 +0x1 fp=0x9148fa4 sp=0x9148fa0 pc=0x80a36c1
created by github.com/shenwei356/seqkit/seqkit/cmd.glob..func30
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/stat.go:285 +0x8e9

goroutine 1 [semacquire, 34 minutes]:
sync.runtime_Semacquire(0x937f088)
        /usr/local/go/src/runtime/sema.go:56 +0x36
sync.(*WaitGroup).Wait(0x937f080)
        /usr/local/go/src/sync/waitgroup.go:130 +0x7c
                                                      
```

**Comment by shenwei356** [comment]
It is a out of memory panic, where seqkit stores lengths of all reads into a list/slice for computing N50, L50, Q1, Q2, and Q3 later. I did not imagine such big FASTQ files. Can you count the files by `wc -l` or
`seqkit stats` without `-a`.

**Comment by moldach** [comment]
I'm able to run `seqkit stats` without `-a` on one file (only).

Not sure what you meant by count the files with `wc -l`? I have 4 files: raw (R1/R2) and cleaned (R1/R2).


```
seqkit stats CG00010P_R1.fastq.gz > Raw_R1_seqkit_report.txt
```

Results in:

```
file                                                   format  type     num_seqs         sum_len  min_len  avg_len  max_len
CG00010P_R1.fastq.gz  FASTQ   DNA   306,912,836  46,343,838,236      151      151	151
```

Which takes:

```
Successfully completed.

Resource usage summary:

    CPU time :                                   10602.27 sec.
    Max Memory :                                 21 MB
    Average Memory :                             21.00 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              4
    Max Threads :                                15
    Run time :                                   10179 sec.
    Turnaround time :                            10178 sec.
```

However, trying the `-a` parameter fails.

**Comment by shenwei356** [comment]
Hi Matthew, I've just fixed this using a faster and memory effective method for length statistics. Sorry for being so late.

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/5283004/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/5283006/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/5283002/seqkit_darwin_amd64.tar.gz)
