### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by aderzelle** [shenwei356/seqkit#197]
### Prerequisites
using:
seqkit v0.15.0

### Describe your issue
Hello, I am getting this error 

```
cat test.fa|seqkit seq -s -w 0|sed -r 's/[Nn]+/\n/g'|cat -n | seqkit tab2fx
>     1

>     2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4f3866]

goroutine 1 [running]:
bytes.(*Buffer).Write(0x0, 0xc0001600e0, 0x3c, 0xe0, 0xc0001600e0, 0xc0004b00f7, 0xdb)
	/usr/local/go/src/bytes/buffer.go:169 +0x26
github.com/shenwei356/util/byteutil.(*BufferedByteSliceWrapper).Wrap(0xc0005140f0, 0xc0001600e0, 0xdb, 0xe0, 0x3c, 0xe0, 0x8, 0x0, 0x0)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/shenwei356/util@v0.0.0-20201214054755-2942125340cd/byteutil/util.go:140 +0x133
github.com/shenwei356/seqkit/seqkit/cmd.glob..func33(0x110b860, 0x11429b8, 0x0, 0x0)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/tab2fx.go:133 +0x65a
github.com/spf13/cobra.(*Command).execute(0x110b860, 0x11429b8, 0x0, 0x0, 0x110b860, 0x11429b8)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1109100, 0x11146e0, 0x0, 0xc00005a778)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/shenwei356/seqkit/seqkit/cmd.Execute()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/root.go:53 +0x31
main.main()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/main.go:58 +0x25
```

I am on ubuntu 20.04.2 LTS

Here is the test.fa 

```
>18_Helicarionidae_Fastosarion_virens_02
NNnATGTCGAATCCATTTTTCCCATCTTGTTTGCCAAAGGTAGATGATTCTTTGTGGTTTAATGTTGATAAG
CCCAGGGACGACGAAAATGAACTCACCGTTTTGGAGGAAAGGCACAACTCTTGGATGAATGCAATAGCTATG
AAAGATAATAATATTGTGCCTATTGGAAAATCAACTGAGCATCCTGATGGTGAGGAGGAGGAAGAAGAGGAG
GAAGAANNNTGTGAAGAAGAGGAGGAAGAGAGTGATACAAATGATGACNNNCCTGACACAGATATGATGGAT
GAAAGAGACTCAAATGATGACGCAAGCACTTATTGANNNNNn
>39_Camaenidae_Ramogenia_challengeri_03
NNnATGTCGAATCCGTACTTCCCGTCATTGTTACCAAAAGTCGATGATTCTTTGTGGTTTAATGTCGACAAA
CCAAGAGACGACGAAAATGAACTCACGGTGTTGGAGGAAAGACATAGTGCCTGGATGAATGCAATTGCTTTG
AAAGACAATAATGTTGTGCCTATTGGAAAGTCAACAGAGCACCCAGAAGGTGAGGAGGAGGAAGAAGATGAA
```

Thank you

**Comment by shenwei356** [comment]
It's a rare bug.

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6119747/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6119749/seqkit_linux_amd64.tar.gz)


It seems you want to split scaffolds into contigs:

```
cat test.fa \
    | seqkit seq -s -w 0 \
    | sed -r 's/[Nn]+/\n/g' \
    | cat -n \
    | seqkit tab2fx \
    | seqkit seq -m 1 \
    | seqkit replace -p .+ -r {nr}

```

**Comment by aderzelle** [comment]
worked well, thank you
